usuarios/applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'panel/',
        views.HomePage.as_view(),
        name='home-panel'
    ),
]

usuarios/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'create/',
        views.UserCreateView.as_view(),
        name='usercreate'
    ),
    path(
        'login/',
        views.LoginUsers.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'PassUpdate/',
        views.UpdatePasswordView.as_view(),
        name='user-UpdatePassword',
    ),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

# Managers locales
from .managers import UserManager

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    username = models.CharField(max_length=15, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30, blank=True)
    apellidos = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

usuarios/applications/users/forms.py
from pyexpat import model
from django import forms
from django.contrib.auth import authenticate

from .models import User


class UserCreateForm(forms.ModelForm):

    password1 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Contraseña'
                   }
        )
    )

    password2 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Repetir Contraseña'
                   }
        )
    )

    class Meta:

        model = User
        fields = (
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero'
        )

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error(
                'password2', 'Las contraseñas no son identicas verificar')


class LoginForm(forms.Form):
    username = forms.CharField(
        label="username",
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'username',
                'style': '{ margin: 10px }',
            }
        )
    )
    password = forms.CharField(
        label="password",
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuarios no correctos')

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    password1 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Contraseña Actual '
                   }
        )
    )

    password2 = forms.CharField(
        label=("Contraseña"),
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': 'Contraseña Nueva '
                   }
        )
    )

usuarios/applications/home/views.py
import datetime

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

from django.views.generic import (
    TemplateView,
)


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class HomePage(LoginRequiredMixin, FechaMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:user-login')

usuarios/applications/users/views.py
from .models import User
import datetime

from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

# Create your views here.

from django.views.generic import (
    View,
    CreateView,
)

from django.views.generic.edit import (
    FormView,
)

from .forms import (
    UserCreateForm,
    LoginForm,
    UpdatePasswordForm,
)


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class UserCreateView(FechaMixin, FormView):
    template_name = 'users/create.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('home_app:home-panel')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['password1'],
            form.cleaned_data['email'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            genero=form.cleaned_data['genero'],
        )
        #
        return super(UserCreateView, self).form_valid(form)


class LoginUsers(FechaMixin, FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:home-panel')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUsers, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FechaMixin, FormView):
    template_name = 'users/UpdateLogin.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1']
        )
        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()
            logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<h1>Panel de Usuaurios </h1>

<h3>Bienvenidos: {{user}} </h3>

<h3>Fecha actual: {{fecha}}</h3>

<ul>
    <li><a href="{% url 'users_app:user-logout' %}">Cerrar Sesion </a></li>
    <li><a href="{% url 'users_app:user-UpdatePassword' %}">Actualizar Datos </a></li>
</ul>

<body>

</body>

</html>

usuarios/templates/users/UpdateLogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Cambiar la contraseña del usuario: {{user.get_full_name}}</h1>

    <p>La fecha: {{fecha}}</p>
    <form method="post"> {% csrf_token %}

        {{form.as_p}}

        <button type="submit">Actualizar </button>

    </form>
</body>

</html>

usuarios/templates/users/create.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<h1>Registrar usuario del funcionario </h1>

<form method="post">{% csrf_token %}
    {{form.as_p}}

    <button type="submit">Registrar</button>
</form>

<body>

</body>

</html>

usuarios/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Acceder al sistema </h1>


    <form method="post"> {% csrf_token %}

        {{form.as_p}}


        <button type="submit"> Acceder al sistema </button>

    </form>

    <p>Fecha actual: {{fecha}}</p>
</body>

</html>